[package]
name = "titan"
version = "0.1.0"
authors = ["Eric Dattore <edattore@gmail.com>"]

[lib]
path = "src/lib.rs"
name = "libtitan"

[[bin]]
path = "src/bin/main.rs"
name = "titan"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
regex = "1.0.5"
bcrypt = "0.2.0"
frank_jwt = "3.0.0"
rocket = "0.4.0-rc.1"
rocket_cors = "0.4.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
features = ["json", "databases", "diesel_mysql_pool"]

[dependencies.diesel]
version = "1.0"
features = ["mysql", "r2d2", "serde_json"]