sudo: required
services:
- docker
dist: trusty
language: node_js
node_js:
- '9'
stages:
- name: Tests
- name: Deploy Staging
  if: type = pull_request
- name: Deploy Production
  if: branch = master AND type != pull_request
- name: Build Docker Image
  if: branch = master AND type = cron
before_install:
- docker pull unkso/titan-image
jobs:
  include:
  - stage: Tests
    script: docker run -v $(pwd):/app unkso/titan-image /bin/bash -c "cd titan-web-client
      && yarn && yarn test"
  - stage: Tests
    script: docker run -v $(pwd):/app unkso/titan-image /bin/bash -c "cd titan-server
      && cargo test"
  - stage: Build Docker Image
    script: scripts/build-and-push-docker-image.sh
env:
  global:
  - secure: JNy2ccgjDBwl+2oo/QTVCziDufx7WATI9lpHwWxvI6JYlqRy9TW23fOr6/9SwgYJYOd59h+XI9LQ7c5t4B1JQ5UFWWJQB1fxbK5OMtK+78WVFaYjXfQwXYFCMWATnP8PR8xsWUdGcvaMdjXfgxAcS2ctK6saSsNRMX/YhF+2QkKodqD1g7H/1MiYO8lLHVQ4BVPwhnnwRQM8yoBBd5nUFIssbJ6Ouqij/W2cdTXKdEH2Z2CP/NCISrVREHaxWNZwZI1oov59N6VbW0lb/6qVbWFbzrubgdj1SWAMIW4W207oh4+mXRFsrQkRgznxMyDcq9oYgRkLPj26omZS0G4ffaZXkowv6p9A/nrWkMeUNeJntX8P0j5z+GSz1bzfuhq3LqGbWHFezymoKUW5Lvq63YgOSmHqN7hp78gRr5lJQlDTfjBjRNgeTZB4OarYWAHI5rpT68mHuyj3e9AB9oLpaIU6YedXD97LUokPQHJzs+MuvMXDqyzHGksSsOlNF1a9RTJPVmlxYv/oyGpWpwE2VSjQNKYnd8jmnmN2Ah61GZ+sh0/ZUaznf2PW5GCn/3eoQr5scEZLW67c/hKhQ7bDaeMqkFJyGOG94+c99ZW41w9IJ6cMJdKIhd3ae6TfthB1rwerSxODqEsivO8SBemffTHl9iQ4jZqFVqRSCMDjQHs=
  - secure: cpkpOjgHG55oo/G+aTJJSSd/jCGmhen1NC5dKo87VTuP15RYIfwHV4TTd+2uZAqj+Qb/5qGSDU4ZO+k9eP3/pSpHS0klyoCvr850BQXwLDbKSPjlTvnl6wuAyQRbGr7mmSDbJfkKFvaRUObMockhYmdYDCHjp/ZCUY95XWAn7dALFi2WDEP/MLTkSBkZcAphk9anoJl03vUlEtlxZPeL2RIwyhoEO0KKNK6inocWmv4DCc97g2yjPt3GR5QS9XFnVEIXecDgfQNqYe/JVn0tM5lDNNiFkkdOwwEVsUhg8FcTG5zNhzNjJskQX0FAkCs1AcPchGxxQUpE6FD9ti+sU4vRoZlFcXouFj8QNeoxz8/u9U0Dzq4CQrPKJNHzv8aWUpQMk+WCSxDkeX+L3x4/Ty/zywYxlnCTM6pvyZft3Enrma2AscBCaTDZ0uiyqpVbO5OCwso3l5GN2G+J6+lsk/feUQJPlcV0toDazymtX2Unv8FEYo8ag8sJoqY+/kGKwEXwPWo8hMdXOSPD/0GbEFzQ0LxprLNOBuS5s+C1fgMK6QzmHHEQ36KldGCLyo9WJuoER/y8tncYJy1JHTpf059d4Cc06bWMsKx9EsNYjmTKpGJ19bBzfi4h21nTsPEvO9EAOhenWDbhKRALhK3uWB5yYwL5b1U3KiVEtj6HTak=
