sudo: required
services:
- docker
dist: trusty
language: node_js
node_js:
- '9'
stages:
- name: Tests
- name: Deploy Staging
  if: type = pull_request
- name: Deploy Production
  if: branch = master AND type != pull_request
- name: Build Docker Image
  if: branch = master AND type = cron
before_install:
- docker pull unkso/titan-image
jobs:
  include:
  - stage: Tests
    script: docker run -v $(pwd):/app unkso/titan-image /bin/bash -c "cd titan-web-client
      && yarn && yarn test"
  - stage: Tests
    script: docker run -v $(pwd):/app unkso/titan-image /bin/bash -c "cd titan-server
      && cargo test"
  - stage: Build Docker Image
    script: scripts/build-and-push-docker-image.sh
env:
  global:
  - secure: JNy2ccgjDBwl+2oo/QTVCziDufx7WATI9lpHwWxvI6JYlqRy9TW23fOr6/9SwgYJYOd59h+XI9LQ7c5t4B1JQ5UFWWJQB1fxbK5OMtK+78WVFaYjXfQwXYFCMWATnP8PR8xsWUdGcvaMdjXfgxAcS2ctK6saSsNRMX/YhF+2QkKodqD1g7H/1MiYO8lLHVQ4BVPwhnnwRQM8yoBBd5nUFIssbJ6Ouqij/W2cdTXKdEH2Z2CP/NCISrVREHaxWNZwZI1oov59N6VbW0lb/6qVbWFbzrubgdj1SWAMIW4W207oh4+mXRFsrQkRgznxMyDcq9oYgRkLPj26omZS0G4ffaZXkowv6p9A/nrWkMeUNeJntX8P0j5z+GSz1bzfuhq3LqGbWHFezymoKUW5Lvq63YgOSmHqN7hp78gRr5lJQlDTfjBjRNgeTZB4OarYWAHI5rpT68mHuyj3e9AB9oLpaIU6YedXD97LUokPQHJzs+MuvMXDqyzHGksSsOlNF1a9RTJPVmlxYv/oyGpWpwE2VSjQNKYnd8jmnmN2Ah61GZ+sh0/ZUaznf2PW5GCn/3eoQr5scEZLW67c/hKhQ7bDaeMqkFJyGOG94+c99ZW41w9IJ6cMJdKIhd3ae6TfthB1rwerSxODqEsivO8SBemffTHl9iQ4jZqFVqRSCMDjQHs=
  - secure: cpkpOjgHG55oo/G+aTJJSSd/jCGmhen1NC5dKo87VTuP15RYIfwHV4TTd+2uZAqj+Qb/5qGSDU4ZO+k9eP3/pSpHS0klyoCvr850BQXwLDbKSPjlTvnl6wuAyQRbGr7mmSDbJfkKFvaRUObMockhYmdYDCHjp/ZCUY95XWAn7dALFi2WDEP/MLTkSBkZcAphk9anoJl03vUlEtlxZPeL2RIwyhoEO0KKNK6inocWmv4DCc97g2yjPt3GR5QS9XFnVEIXecDgfQNqYe/JVn0tM5lDNNiFkkdOwwEVsUhg8FcTG5zNhzNjJskQX0FAkCs1AcPchGxxQUpE6FD9ti+sU4vRoZlFcXouFj8QNeoxz8/u9U0Dzq4CQrPKJNHzv8aWUpQMk+WCSxDkeX+L3x4/Ty/zywYxlnCTM6pvyZft3Enrma2AscBCaTDZ0uiyqpVbO5OCwso3l5GN2G+J6+lsk/feUQJPlcV0toDazymtX2Unv8FEYo8ag8sJoqY+/kGKwEXwPWo8hMdXOSPD/0GbEFzQ0LxprLNOBuS5s+C1fgMK6QzmHHEQ36KldGCLyo9WJuoER/y8tncYJy1JHTpf059d4Cc06bWMsKx9EsNYjmTKpGJ19bBzfi4h21nTsPEvO9EAOhenWDbhKRALhK3uWB5yYwL5b1U3KiVEtj6HTak=
  - secure: ox3Bmhf++LMjTunR/d7HAkvaW3i+MXjXge/RYq8kuwSfNaQfQtg4SsYXC4IvZX0VJpwB8tCm6MUrl99pQaUk3oPyiTSOaEWMUhIzuM7W6ZXKpP3WxbOYojzAvGc1bPFb7c/7wuZDOE3wPA7cgOrN7BwVzZaFAgp+wNyxz8QouOoPr+5Uh99j7IwSBjEZq4gR0+7U+Sp6qHzbCCSKBG5L3CzvVWfaOEZFQcz5kW7ImiB2b9ORKcf0Nrjse657zNite6Ly8albnQBO11rUXVPHNffichW1h4gYhz5K/0vGnBMv6jPGEROIv/W6XXwB7tyMDFhJCrMba6Qlx382VXMgALFJcAp+weyELvyoKRaDUAkOoSO2dZ4YG9h9s0MGF5nppqyO+Iqv49IXHpmUKa0GwSLG8zRi4BGrJuCxzUlBimwb108INLM6F10eOnKM6sRjjgRiQLWvyD8QI2D0ToU9E/1xKreo86Dgo0xbvv47S60n9eCk+xNgDTh05ypwlvdTLZmZHcEMgbXl5AKZA4vZxKjdvWNtW6Nxa+bzT+Gc6AUd69IjDMLNdyX4fNDjtJqRqx+VS3ZEwNhQx+pVArrnLltcvx8to9j9fIWaEHok+IBGm/2pd3ESz1AXyVTF+Lxn12pQ1NXHq9x0ahqkPh4KDX+JlRFkSm/2GzLR16Wcegc=
  - secure: ZPAIpak7LBKLxVKZIZg/lbgq6q5DoGYYTdbbN/5L1fE+dODQGt79iQ7QP5dRGDaktIF+5EpH26z5zkLU6OKzU9vLt6n8d0upVgFlShNMxDte66yfK6FnK++al4EmrdqPW26euAKo0B4+R9C7ZtiYjv7P6prAkds09FiB1fSJmKSUUnpxYlJRyB6Sdt9VLpZFI+QtKiHjzVwOAzJLtX0d23lH+Mq4TYMZ+wQqjCC2/yH9af6GaBcs8vRl25PSC0C3fAVJM8GUjSXlz1vNVmoYhhLgs953ebIRxHSNxVgZttK1vEhkXE0uP/uXZzLgEQZR+zI4CVtwPPpuyDHkz7tCO+/4W8a83mlRHIa+0Hfdc+tIu2NRAn5B2DMCusxKZXtpgATLTFDq4fMvwOR36Jd6wOqVgFk3pWkw2J45lAszMBa/+mcw0uOQy+/zWztFDwhxRsa5c3kC7DvEKxBfyrvIp38EMNgbX3VP+phF/Q9DwCebijDi+WwIqXM9HMJWvgoPZdp5gIwEn1lCSFRO5WjJIRLg1sh0+ou2zAdYg+N9oHQLCGeHYycNkLKQBBWtkPAZ0iDpnYkUnotN1ndHAi0Oeqdzv7c4ZjyLfuOlV3NpcWTuLNMIqSeD5MBcJ9aP5l0i6wgZS4lw4LcW2Pk7QT0x9gLDDviQRzZlzWWsNRASaEQ=
